### ISSUE TITLE
NullPointerException when searching any tag

### ISSUE THREAD

**Issue by stndart** [yueeng/moebooru#248]
How to reproduce:
1. Update to 1.0.7
2. Type any keyword ("-loli", for example)
3. Press search
4. Get error
=====BuildConfig=====
=====Exception=====
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:589)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4865)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
	at android.os.Parcel.readValue(Parcel.java:4544)
	at android.os.Parcel.readValue(Parcel.java:4324)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at androidx.activity.q.j(SourceFile:1)
	at com.github.yueeng.moebooru.w3.e(SourceFile:14)
	at f6.h.getValue(SourceFile:1)
	at com.github.yueeng.moebooru.x3.W(SourceFile:1)
	at com.github.yueeng.moebooru.x3.F(SourceFile:97)
	at androidx.fragment.app.c0.O(SourceFile:26)
	at androidx.fragment.app.z0.f(SourceFile:199)
	at androidx.fragment.app.z0.k(SourceFile:147)
	at androidx.fragment.app.t0.z(SourceFile:24)
	at androidx.fragment.app.t0.S(SourceFile:82)
	at androidx.fragment.app.t0.x(SourceFile:77)
	at androidx.fragment.app.t0.t(SourceFile:67)
	at androidx.fragment.app.f0.onStart(SourceFile:34)
	at f.p.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8616)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
-------------------

**Comment by yueeng** [comment]
try v1.0.8

**Comment by stndart** [comment]
Sorry, it was 1.0.8, the most recent one. Also, didn't succeed in downgrading to 1.0.7. It says the "package is invalid (corrupted, for example)"

**Comment by yueeng** [comment]
Version 1.0.9 has been updated. Give it a try.

**Comment by stndart** [comment]
Nope, still doesn't work. The error format changed, though.
===== BuildConfig =====
APPLICATION_ID: "com.github.yueeng.moebooru.yande"
BUILD_TIME: "202403010623"
BUILD_TYPE: "release"
DEBUG: false
FLAVOR: "yande"
VERSION_CODE: 9
VERSION_NAME: "1.0.9"

===== Build =====
BOARD: "a22"
BOOTLOADER: "A225FXXU7DWH3"
BRAND: "samsung"
CPU_ABI: "arm64-v8a"
CPU_ABI2: ""
DEVICE: "a22"
DISPLAY: "TP1A.220624.014.A225FXXU7DWH3"
FINGERPRINT: "samsung/a22nsser/a22:13/TP1A.220624.014/A225FXXU7DWH3:user/release-keys"
HARDWARE: "mt6769t"
HOST: "21DKG913"
ID: "TP1A.220624.014"
IS_DEBUGGABLE: false
IS_EMULATOR: false
MANUFACTURER: "samsung"
MODEL: "SM-A225F"
ODM_SKU: "hcesim"
PERMISSIONS_REVIEW_REQUIRED: true
PRODUCT: "a22nsser"
RADIO: "unknown"
SERIAL: "unknown"
SKU: "hcesim"
SOC_MANUFACTURER: "Mediatek"
SOC_MODEL: "MT6769V/CT"
SUPPORTED_32_BIT_ABIS: ["armeabi-v7a","armeabi"]
SUPPORTED_64_BIT_ABIS: ["arm64-v8a"]
SUPPORTED_ABIS: ["arm64-v8a","armeabi-v7a","armeabi"]
TAGS: "release-keys"
TIME: 1692336126000
TYPE: "user"
UNKNOWN: "unknown"
USER: "dpi"

===== VERSION =====
ACTIVE_CODENAMES: []
BASE_OS: ""
CODENAME: "REL"
INCREMENTAL: "A225FXXU7DWH3"
KNOWN_CODENAMES: ["HoneycombMr1","HoneycombMr2","Lollipop","Kitkat","Tiramisu","Gingerbread","Cupcake","IceCreamSandwichMr1","JellyBean","IceCreamSandwich","LollipopMr1","M","N","O","P","Q","R","S","Sv2","Base","NMr1","OMr1","JellyBeanMr1","JellyBeanMr2","Donut","Froyo","GingerbreadMr1","EclairMr1","Honeycomb","Eclair01","KitkatWatch","Base11","Eclair"]
MEDIA_PERFORMANCE_CLASS: 0
PREVIEW_SDK_FINGERPRINT: "REL"
PREVIEW_SDK_INT: 0
RELEASE: "13"
RELEASE_OR_CODENAME: "13"
RELEASE_OR_PREVIEW_DISPLAY: "13"
SDK: "33"
SDK_INT: 33
SECURITY_PATCH: "2023-08-01"
SEM_FIRST_SDK_INT: 30
SEM_INT: 3301
SEM_PLATFORM_INT: 140100

===== Exception =====
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:589)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4865)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
	at android.os.Parcel.readValue(Parcel.java:4544)
	at android.os.Parcel.readValue(Parcel.java:4324)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at androidx.activity.q.j(SourceFile:1)
	at com.github.yueeng.moebooru.l3.d(SourceFile:14)
	at f6.h.getValue(SourceFile:1)
	at com.github.yueeng.moebooru.m3.W(SourceFile:1)
	at com.github.yueeng.moebooru.m3.F(SourceFile:97)
	at androidx.fragment.app.c0.O(SourceFile:26)
	at androidx.fragment.app.z0.f(SourceFile:199)
	at androidx.fragment.app.z0.k(SourceFile:147)
	at androidx.fragment.app.t0.z(SourceFile:24)
	at androidx.fragment.app.t0.S(SourceFile:82)
	at androidx.fragment.app.t0.x(SourceFile:77)
	at androidx.fragment.app.t0.t(SourceFile:67)
	at androidx.fragment.app.f0.onStart(SourceFile:34)
	at f.p.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8616)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by yueeng** [comment]
Try v1.0.9.1

**Comment by stndart** [comment]
Yep, it works now. Many thanks!
