### ISSUE TITLE
Download error with yande.re version 1.0.8

### ISSUE THREAD

**Issue by laplus114** [yueeng/moebooru#249]
When I try to download images in yande.re 1.0.8, I get the following error. It does not appear in version 1.0.7
`=====BuildConfig=====

=====Exception=====
android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{f94c55a 25170:com.github.yueeng.moebooru.yande/u0a684} targetSDK=34 has been prohibited
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4900)
	at android.os.Parcel.readValue(Parcel.java:4651)
	at android.os.Parcel.readValue(Parcel.java:4420)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4518)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4477)
	at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:415)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:401)
	at android.os.BaseBundle.getValue(BaseBundle.java:381)
	at android.os.BaseBundle.getValue(BaseBundle.java:364)
	at android.os.BaseBundle.get(BaseBundle.java:737)
	at android.os.BaseBundle.getSerializable(BaseBundle.java:1518)
	at android.os.Bundle.getSerializable(Bundle.java:1189)
	at android.content.Intent.getSerializableExtra(Intent.java:9290)
	at androidx.activity.q.h(SourceFile:1)
	at com.github.yueeng.moebooru.CrashActivity.onCreate(SourceFile:32)
	at android.app.Activity.performCreate(Activity.java:8757)
	at android.app.Activity.performCreate(Activity.java:8729)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1475)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3985)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4161)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2627)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
-------------------
`

**Comment by yueeng** [comment]
Thank you for the feedback. I have changed 1.0.8 to pre-release. You can continue using 1.0.7, and I will re-release it after fixing the bugs.

**Comment by laplus114** [comment]
Version v1.0.9 does not have this download error, thanks for your work!
